URL_BY_CATALOG = {
    "type": "GET_TYPE",
    "pokedex": "GET_POKEDEX",
    "egg-group": "GET_EGG_GROUP",
    "gender": "GET_GENDER",
    "habitat": "GET_HABITAT",
    "growth-rate": "GET_GROWTH_RATE",
}

THEME_BY_CATALOG = {
    "growth-rate": {
        "slow": {"icon": "img/growthRate/test", "color": "#FF0000", "background-img": "img/growthRate/bg"},
        "medium": {"icon": "img/growthRate/test", "color": "#FF0000", "background-img": "img/growthRate/bg"},
        "fast": {"icon": "img/growthRate/test", "color": "#FF0000", "background-img": "img/growthRate/bg"},
        "medium-slow": {"icon": "img/growthRate/test", "color": "#FF0000", "background-img": "img/growthRate/bg"},
        "slow-then-very-fast": {"icon": "img/growthRate/test", "color": "#FF0000",
                                "background-img": "img/growthRate/bg"},
        "fast-then-very-slow": {"icon": "img/growthRate/test", "color": "#FF0000",
                                "background-img": "img/growthRate/bg"}
    },
    "habitat": {
        "cave": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},
        "forest": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},

        "grassland": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},
        "mountain": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},
        "rare": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},
        "rough-terrain": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},
        "sea": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},
        "urban": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"},
        "waters-edge": {"icon": "img/habitat/test", "color": "#FF0000", "background-img": "img/habitat/bg"}
    },
    "gender": {
        "female": {'icon': "img/gender/test", "color": "#FF000", "background-img": "img/gender/bg"},
        "male": {'icon': "img/gender/test", "color": "#FF000", "background-img": "img/gender/bg"},
        "genderless": {'icon': "img/gender/test", "color": "#FF000", "background-img": "img/gender/bg"},
    },
    "egg-group": {
        "monster": {'icon': "img/eggGroup/oeuf_monster.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "water1": {'icon': "img/eggGroup/oeuf_water1.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "bug": {'icon': "img/eggGroup/test", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "flying": {'icon': "img/eggGroup/oeuf_flying.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "ground": {'icon': "img/eggGroup/oeuf_ground.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "fairy": {'icon': "img/eggGroup/oeuf_fairy.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "plant": {'icon': "img/eggGroup/oeuf_plant.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "humanshape": {'icon': "img/eggGroup/oeuf_humanshape.png", "color": "#FF000",
                       "background-img": "img/eggGroup/bg"},
        "water3": {'icon': "img/eggGroup/oeuf_water3.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "mineral": {'icon': "img/eggGroup/oeuf_mineral.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "indeterminate": {'icon': "img/eggGroup/oeuf_indeterminate.png", "color": "#FF000",
                          "background-img": "img/eggGroup/bg"},
        "water2": {'icon': "img/eggGroup/oeuf_water2.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "ditto": {'icon': "img/eggGroup/oeuf_ditto.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "dragon": {'icon': "img/eggGroup/oeuf_dragon.png", "color": "#FF000", "background-img": "img/eggGroup/bg"},
        "no-eggs": {'icon': "img/eggGroup/oeuf_no-eggs.png", "color": "#FF000", "background-img": "img/eggGroup/bg"}
    },
    "pokedex": {
        "national": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "kanto": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-johto": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "hoenn": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-sinnoh": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "extended-sinnoh": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "updated-johto": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-unova": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "updated-unova": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "conquest-gallery": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "kalos-central": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "kalos-coastal": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "kalos-mountain": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "updated-hoenn": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-alola": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-melemele": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-akala": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-ulaula": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "original-poni": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"},
        "updated-alola": {'icon': "img/pokedex/test", "color": "#FF000", "background-img": "img/pokedex/bg"}
    },
    "type": {
        "fire": {'icon': "img/types/fire.svg", "color": "#FFD1B2", "background-img": "img/types/bg",
                 "background_color": "#FFC59B"},
        "water": {'icon': "img/types/water.svg", "color": "#AED4FF", "background-img": "img/types/bg",
                  "background_color": "#88C3FF"},
        "grass": {'icon': "img/types/grass.svg", "color": "#B1FCA0", "background-img": "img/types/bg",
                  "background_color": "#92F589"},
        "electric": {'icon': "img/types/electric.svg", "color": "#FFFFA1", "background-img": "img/types/bg",
                     "background_color": "#FFFF8A"},
        "ice": {'icon': "img/types/ice.svg", "color": "#B4FAF1", "background-img": "img/types/bg",
                "background_color": "#90F6E6"},
        "fighting": {'icon': "img/types/fighting.svg", "color": "#FFB4C9", "background-img": "img/types/bg",
                     "background_color": "#FF96B4"},
        "poison": {'icon': "img/types/poison.svg", "color": "#E2B0FF", "background-img": "img/types/bg",
                   "background_color": "#D498EE"},
        "ground": {'icon': "img/types/ground.svg", "color": "#EEC5A6", "background-img": "img/types/bg",
                   "background_color": "#E9AB8C"},
        "flying": {'icon': "img/types/flying.svg", "color": "#C1D2F0", "background-img": "img/types/bg",
                   "background_color": "#AEC1EB"},
        "psychic": {'icon': "img/types/psychic.svg", "color": "#FFB3B0", "background-img": "img/types/bg",
                    "background_color": "#FF9195"},
        "bug": {'icon': "img/types/bug.svg", "color": "#E2FF95", "background-img": "img/types/bg",
                "background_color": "#CEFE6C"},
        "rock": {'icon': "img/types/rock.svg", "color": "#F8EAC3", "background-img": "img/types/bg",
                 "background_color": "#F5E0A9"},
        "ghost": {'icon': "img/types/ghost.svg", "color": "#C8D4F7", "background-img": "img/types/bg",
                  "background_color": "#B3C2EF"},
        "dark": {'icon': "img/types/dark.svg", "color": "#9A9A9D", "background-img": "img/types/bg",
                 "background_color": "#817F83"},
        "dragon": {'icon': "img/types/dragon.svg", "color": "#6FB3FF", "background-img": "img/types/bg",
                   "background_color": "#3CA4FF"},
        "steel": {'icon': "img/types/steel.svg", "color": "#C3D9E0", "background-img": "img/types/bg",
                  "background_color": "#A7C6D3"},
        "fairy": {'icon': "img/types/fairy.svg", "color": "#FFC0FB", "background-img": "img/types/bg",
                  "background_color": "#FFA7F9"},
        "normal": {'icon': "img/types/normal.svg", "color": "#E0E0E0", "background-img": "img/types/bg",
                   "background_color": "#CCCCCC"},
    }
}
