URL_BY_CATALOG = {
    "type": "GET_TYPE",
    "pokedex": "GET_POKEDEX",
    "egg-group": "GET_EGG_GROUP",
    "gender": "GET_GENDER",
    "habitat": "GET_HABITAT",
    "growth-rate": "GET_GROWTH_RATE",
}

THEME_BY_CATALOG = {
    "growth-rate": {
        "slow": {"icon": "img/growthRate/slow.png", "color": "#d4efdf"},
        "medium": {"icon": "img/growthRate/medium.png", "color": "#abebc6"},
        "fast": {"icon": "img/growthRate/fast.png", "color": "#aed6f1"},
        "medium-slow": {"icon": "img/growthRate/medium-slow.png", "color": "#a9cce3"},
        "slow-then-very-fast": {"icon": "img/growthRate/slow-then-very-fast.png", "color": "#d2b4de",},
        "fast-then-very-slow": {"icon": "img/growthRate/fast-then-very-slow.png", "color": "#f5b7b1",}
    },
    "habitat": {
        "cave": {"icon": "img/habitat/cave.png", "color": "#6F61A7"},
        "forest": {"icon": "img/habitat/forest.png", "color": "#68D098"},

        "grassland": {"icon": "img/habitat/grassland.png", "color": "#94E436"},
        "mountain": {"icon": "img/habitat/mountain.png", "color": "#BC9436"},
        "rare": {"icon": "img/habitat/rare.png", "color": "#B4C55A"},
        "rough-terrain": {"icon": "img/habitat/rough-terrain.png", "color": "#E0B050",
                          "background-img": "img/habitat/bg"},
        "sea": {"icon": "img/habitat/sea.png", "color": "#6860F8"},
        "urban": {"icon": "img/habitat/urban.png", "color": "#A8B0C8"},
        "waters-edge": {"icon": "img/habitat/waters-edge.png", "color": "#AEB2A9"}
    },
    "gender": {
        "female": {'icon': "img/gender/female.png", "color": "#fadbd8"},
        "male": {'icon': "img/gender/male.png", "color": "#d6eaf8"},
        "genderless": {'icon': "img/gender/genderless.png", "color": "#f2f3f4"},
    },
    "egg-group": {
        "monster": {'icon': "img/eggGroup/monster.png", "color": "#404040"},
        "water1": {'icon': "img/eggGroup/water1.png", "color": "#379EFF"},
        "bug": {'icon': "img/eggGroup/bug.png", "color": "#5C245C"},
        "flying": {'icon': "img/eggGroup/flying.png", "color": "#B7B6B3"},
        "ground": {'icon': "img/eggGroup/ground.png", "color": "#FBBD47"},
        "fairy": {'icon': "img/eggGroup/fairy.png", "color": "#B94A00"},
        "plant": {'icon': "img/eggGroup/plant.png", "color": "#A1F173"},
        "humanshape": {'icon': "img/eggGroup/humanshape.png", "color": "#E8E0A0"},
        "water3": {'icon': "img/eggGroup/water3.png", "color": "#379DFD"},
        "mineral": {'icon': "img/eggGroup/mineral.png", "color": "#6F87B5"},
        "indeterminate": {'icon': "img/eggGroup/indeterminate.png", "color": "#9DF68E"},
        "water2": {'icon': "img/eggGroup/water2.png", "color": "#00FFBE"},
        "ditto": {'icon': "img/eggGroup/ditto.png", "color": "#FFE600"},
        "dragon": {'icon': "img/eggGroup/dragon.png", "color": "#FF0006"},
        "no-eggs": {'icon': "img/eggGroup/no-eggs.png", "color": "#515262"}
    },
    "pokedex": {
        "national": {'icon': "img/pokedex/national.png", "color": "#F7903A"},
        "kanto": {'icon': "img/pokedex/kanto.png", "color": "#3A90F7"},
        "original-johto": {'icon': "img/pokedex/original-johto.png", "color": "#eec42d"},
        "hoenn": {'icon': "img/pokedex/hoenn.png", "color": "#de1ebe"},
        "original-sinnoh": {'icon': "img/pokedex/original-sinnoh.png", "color": "#51935e"},
        "extended-sinnoh": {'icon': "img/pokedex/extended-sinnoh.png", "color": "#2c93c6"},
        "updated-johto": {'icon': "img/pokedex/updated-johto.png", "color": "#fbe09c"},
        "original-unova": {'icon': "img/pokedex/original-unova.png", "color": "#f7933a"},
        "updated-unova": {'icon': "img/pokedex/updated-unova.png", "color": "#a68241"},
        "conquest-gallery": {'icon': "img/pokedex/conquest-gallery.png", "color": "#db8ab8"},
        "kalos-central": {'icon': "img/pokedex/kalos-central.png", "color": "#79889a"},
        "kalos-coastal": {'icon': "img/pokedex/kalos-coastal.png", "color": "#547bd6"},
        "kalos-mountain": {'icon': "img/pokedex/kalos-mountain.png", "color": "#738dc4"},
        "updated-hoenn": {'icon': "img/pokedex/updated-hoenn.png", "color": "#ee9382"},
        "original-alola": {'icon': "img/pokedex/original-alola.png", "color": "#e6883f"},
        "original-melemele": {'icon': "img/pokedex/original-melemele.png", "color": "#e1d53d"},
        "original-akala": {'icon': "img/pokedex/original-akala.png", "color": "#b0593c"},
        "original-ulaula": {'icon': "img/pokedex/original-ulaula.png", "color": "#f58939"},
        "original-poni": {'icon': "img/pokedex/original-poni.png", "color": "#79c03a"},
        "updated-alola": {'icon': "img/pokedex/updated-alola.png", "color": "#47b1c0"}
    },
    "type": {
        "fire": {'icon': "img/types/fire.svg", "color": "#FFD1B2"},
        "water": {'icon': "img/types/water.svg", "color": "#AED4FF"},
        "grass": {'icon': "img/types/grass.svg", "color": "#B1FCA0"},
        "electric": {'icon': "img/types/electric.svg", "color": "#FFFFA1"},
        "ice": {'icon': "img/types/ice.svg", "color": "#B4FAF1"},
        "fighting": {'icon': "img/types/fighting.svg", "color": "#FFB4C9"},
        "poison": {'icon': "img/types/poison.svg", "color": "#E2B0FF"},
        "ground": {'icon': "img/types/ground.svg", "color": "#EEC5A6"},
        "flying": {'icon': "img/types/flying.svg", "color": "#C1D2F0"},
        "psychic": {'icon': "img/types/psychic.svg", "color": "#FFB3B0"},
        "bug": {'icon': "img/types/bug.svg", "color": "#E2FF95"},
        "rock": {'icon': "img/types/rock.svg", "color": "#F8EAC3"},
        "ghost": {'icon': "img/types/ghost.svg", "color": "#C8D4F7"},
        "dark": {'icon': "img/types/dark.svg", "color": "#9A9A9D"},
        "dragon": {'icon': "img/types/dragon.svg", "color": "#6FB3FF"},
        "steel": {'icon': "img/types/steel.svg", "color": "#C3D9E0"},
        "fairy": {'icon': "img/types/fairy.svg", "color": "#FFC0FB"},
        "normal": {'icon': "img/types/normal.svg", "color": "#E0E0E0"},
    }
}
